---
apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
  - ../default
images:
  - name: quay.io/opendatahub/odh-notebook-controller
    newName: quay.io/mroman_redhat/odh-notebook-controller
    newTag: dev-1
